etcd: etcd --data-dir /tmp/etcd.data$PORT
doorman: $GOPATH/bin/doorman -logtostderr -config=./config.yml -port=$PORT -debug_port=$(expr $PORT + 50) -etcd_endpoints=http://localhost:2379 -master_election_lock=/doorman.master -hostname=localhost

